version: '2'
services:
  restyaboard:
    build: .
    expose:
      - 80
    networks:
      - webproxy
    volumes:
       - /mnt/media/Library/Docker/kanban-board/data/:/usr/share/nginx/html/media
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
      - SMTP_DOMAIN=domain
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=pass
      - SMTP_SERVER=server
      - SMTP_PORT=465
      - TZ=Etc/UTC
      - LETSENCRYPT_HOST=kb.jbad.io
      - LETSENCRYPT_EMAIL=joe307bad@gmail.com
      - VIRTUAL_HOST=kb.jbad.io
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
    restart: always
